import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import {userEffect} from "react"
import axios from "axios";
import { Divider } from "semantic-ui-react";
import listArray from "../todo_text_holder"
// import { parseCookies } from "nookies";

const index = (posts) => {
  return (
    <>
    < div className={styles.container}>
      <Head>
        <title>ToDo Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Group List
        </h1>

        
      {posts.listArray.map((post) => {
        return (
          <div key={post.id}>
            <h1>{post.title}</h1>
            <p>{post.body}</p>
            <Divider />
          </div>
        );
      })}

      </main>
      </div>
      </>
  )}

  index.getInitialProps = async (ctx) => {
        // const cookie = parseCookies(ctx)
        const res = await axios.get(
          "https://jsonplaceholder.typicode.com/todos"
        );
        // console.log(ctx);
        return { posts: res.data };
      };
  

      export default index;

